-type(net()::{[atom()], dict()} | {[{atom(), atom()}], dict()}).
-define(NOISE_AVG, -75.0).
-define(NOISE_DELTA, 5.0).
-define(SENSITIVITY, 4.0).
-define(NODENAME, "eliot").
-define(INTERFACE, "wlan0").
-define(RPC_NOACKS, 30000).
-type swtype() :: gettimeofday | clock_gettime | clock | times | getrusage.
-record(stopwatch, {type = gettimeofday :: swtype(), start = none, cur = none, startacc = none, acc = none, last = none}).
